services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
      ELASTIC_PASSWORD: ${ES_PASS}
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped
  visit_sched:
    container_name: visit_sched
    build:
      context: ${VISIT_SCHED_PATH}  # change .env to path to visit_sched repo
      target: dev
    image: visit-scheduler:dev
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
      - broker
    env_file: .env
    volumes:
      - ${VISIT_SCHED_PATH}//visit_scheduler:/app/visit_scheduler
  firestore_emulator:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}
      - PORT=${FIRESTORE_EMULATOR_PORT}
    ports:
      - ${FIRESTORE_EMULATOR_PORT}:${FIRESTORE_EMULATOR_PORT}
  user_chat:
    container_name: user_chat
    build:
      context: ${USER_CHAT_PATH}  # change .env to path to visit_sched repo
      target: dev
    image: user-chat:dev
    ports:
      - 8081:8081
    depends_on:
      - firestore_emulator
      - broker
    environment:
      - FIRESTORE_EMULATOR_HOST=${FIRESTORE_EMULATOR_HOST}:${FIRESTORE_EMULATOR_PORT}
    volumes:
      - ${USER_CHAT_PATH}//user_chat:/app/user_chat
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  visit_manager:
    container_name: visit_manager
    build:
      context: ${VISIT_MANAGER_PATH}  # change .env to path to visit_sched repo
      target: dev
    image: visit-manager:dev
    ports:
      - 8082:8082
    depends_on:
      - postgres
      - broker
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
    volumes:
      - ${VISIT_MANAGER_PATH}//visit_manager:/app/visit_manager
  frontend:
    container_name: frontend
    build:
      context: ${FRONTEND_PATH}  # change .env to path to visit_sched repo
    ports:
      - 3000:3000
  broker:
    image: apache/kafka:4.0.0
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - 9092:9092
      - 9093:9093
    healthcheck:
      test: ["CMD-SHELL", "echo 'test-message' | kafka-console-producer.sh --broker-list broker:9092 --topic health-check-topic && kafka-console-consumer.sh --bootstrap-server broker:9092 --topic health-check-topic --from-beginning --max-messages 1 | grep 'test-message'"]
      interval: 5s
      timeout: 3s
      retries: 60
  
volumes:
  es_data:
    driver: local
  postgres_data:
    driver: local
