services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
      ELASTIC_PASSWORD: abc
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped
  visit_sched:
    image: visit_sched
    container_name: visit_sched
    build: C\CHANG\ME  #  abs path to visit_sched repo
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local
