apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-sched
  namespace: visit-sched-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visit-sched
  template:
    metadata:
      labels:
        app: visit-sched
    spec:
      containers:
        - name: visit-sched
          image: gambolkf/ersms-visit_sched:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: visit-sched
          env:
            - name: ES_CACERT
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-cacert
                  key: ersms-test-elasticsearch-cacert
            - name: ES_LOGIN
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-root-user
                  key: ersms-test-elasticsearch-root-user
            - name: ES_PASS
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-root-password
                  key: ersms-test-elasticsearch-root-password
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /docs
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
