apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: visit-sched-healthcheck
  namespace: visit-sched-ns
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTPS
      httpsHealthCheck:
        portSpecification: USE_SERVING_PORT
        # port: PORT
        # portName: PORT_NAME
        # host: HOST
        requestPath: /api/visit-sched/docs
        # response: RESPONSE
        # proxyHeader: PROXY_HEADER
      # httpsHealthCheck:
      #   portSpecification: PORT_SPECIFICATION
      #   port: PORT
      #   portName: PORT_NAME
      #   host: HOST
      #   requestPath: REQUEST_PATH
      #   response: RESPONSE
      #   proxyHeader: PROXY_HEADER
  targetRef:
    group: ""
    kind: Service
    name: visit-sched-service
    namespace: visit-sched-ns
