apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-sched
  namespace: visit-sched-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visit-sched
  template:
    metadata:
      labels:
        app: visit-sched
    spec:
      serviceAccountName: visit-sched
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: visit-sched
          image: gambolkf/ersms-visit_sched@sha256:d07b97608b3e6a504dd522652c6cc3341fd1c07d33e984f06b8911d96424893d
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: visit-sched
          env:
            - name: ES_CACERT
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-cacert
                  key: ersms-elasticsearch-cacert
            - name: ES_LOGIN
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-root-user
                  key: ersms-elasticsearch-root-user
            - name: ES_PASS
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-root-password
                  key: ersms-elasticsearch-root-password
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /api/visit-sched/docs
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
