apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: ersms-visit-sched@ersms-461920.iam.gserviceaccount.com
  name: visit-sched
  namespace: visit-sched-ns
