apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: visit-sched-gcp-secret-store
  namespace: visit-sched-ns
spec:
  provider:
    gcpsm:
      projectID: ersms-454513
      auth:
        workloadIdentity:
          clusterLocation: europe-west2-a
          clusterName: ersms-test-gke
          clusterProjectID: ersms-454513
          serviceAccountRef:
            name: external-secrets
