apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: visit-sched-elasticsearch-cacert
  namespace: visit-sched-ns
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: visit-sched-gcp-secret-store
  target:
    # name of the k8s Secret to be created
    name: elasticsearch-cacert
    creationPolicy: Owner
  data:
    # name of the GCPSM secret key
  - secretKey: ersms-test-elasticsearch-cacert
    remoteRef:
      key: ersms-test-elasticsearch-cacert

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: visit-sched-elasticsearch-root-password
  namespace: visit-sched-ns
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: visit-sched-gcp-secret-store
  target:
    # name of the k8s Secret to be created
    name: elasticsearch-root-password
    creationPolicy: Owner
  data:
    # name of the GCPSM secret key
  - secretKey: ersms-test-elasticsearch-root-password
    remoteRef:
      key: ersms-test-elasticsearch-root-password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: visit-sched-elasticsearch-root-user
  namespace: visit-sched-ns
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: visit-sched-gcp-secret-store
  target:
    # name of the k8s Secret to be created
    name: elasticsearch-root-user
    creationPolicy: Owner
  data:
    # name of the GCPSM secret key
  - secretKey: ersms-test-elasticsearch-root-user
    remoteRef:
      key: ersms-test-elasticsearch-root-user
