# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: h4h-ingress
#   annotations:
#     # kubernetes.io/ingress.class is deprecated, but GKE needs it!
#     # https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#deprecated_annotation
#     kubernetes.io/ingress.class: "gce"
#     cloud.google.com/load-balancer-type: "External"
#     kubernetes.io/ingress.allow-http: "true"
#     kubernetes.io/ingress.global-static-ip-name: ersms-test-ingress-external-alb-ipv4"
# spec:
#   defaultBackend:
#     service:
#       name: web
#       port:
#         number: 8080
