apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: visit-man-postgres-password
  namespace: visit-man-ns
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: visit-man-gcp-secret-store
  target:
    # name of the k8s Secret to be created
    name: postgres-password
    creationPolicy: Owner
  data:
    # name of the GCPSM secret key
  - secretKey: ersms-postgres-root-password
    remoteRef:
      key: ersms-postgres-root-password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: visit-man-stripe-api-key
  namespace: visit-man-ns
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: visit-man-gcp-secret-store
  target:
    # name of the k8s Secret to be created
    name: stripe-api-key
    creationPolicy: Owner
  data:
    # name of the GCPSM secret key
  - secretKey: ersms-stripe-api-key
    remoteRef:
      key: ersms-stripe-api-key
