apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: user-chat-gcp-secret-store
  namespace: user-chat-ns
spec:
  provider:
    gcpsm:
      projectID: ersms-461920
      auth:
        workloadIdentity:
          clusterLocation: europe-west2-a
          clusterName: ersms-gke
          clusterProjectID: ersms-461920
          serviceAccountRef:
            name: external-secrets
